// main/src/Portfolio.jsx
const { useState } = React;
const { createRoot } = ReactDOM;

const PortfolioComponent = (props) => {
    return (
        <section className="pt-page" data-id="portfolio">
            <div className="section-inner custom-page-content">
                <div className="page-header color-1">
                    <h2>Portfolio</h2>
                </div>
                <div className="page-content">

                    <ul id="portfolio_filters" className="portfolio-filters">
                        <li className="active">
                            <a className="filter btn btn-sm btn-link active" data-group="all">All</a>
                        </li>
                        <li>
                            <a className="filter btn btn-sm btn-link" data-group="code">Code</a>
                        </li>
                        <li>
                            <a className="filter btn btn-sm btn-link" data-group="photo">Photography</a>
                        </li>
                        <li>
                            <a className="filter btn btn-sm btn-link" data-group="hdr">HDR</a>
                        </li>
                        <li>
                            <a className="filter btn btn-sm btn-link" data-group="shop">Photoshop</a>
                        </li>
                        <li>
                            <a className="filter btn btn-sm btn-link" data-group="solid">SolidWorks</a>
                        </li>
                    </ul>

                    <div id="portfolio_grid" className="portfolio-grid">
                        <figure className="item" data-groups='["all", "code"]'>
                            <a className="ajax-page-load" href="pages/project/project-8.html">
                                <img className="img-fluid img-thumbnail" src="./images/portfolio/askS.jpg" alt="" />
                                <div>
                                    <h5 className="name">Ask Ethan!</h5>
                                </div>
                            </a>
                        </figure>

                        <figure className="item" data-groups='["all", "photo"]'>
                            <a className="d-block h-100" data-fancybox="photo" href="images/portfolio/favColorL.jpg">
                                <img className="img-fluid img-thumbnail" src="./images/portfolio/favColorS.jpg" alt="" />
                            </a>
                        </figure>

                        <figure className="item" data-groups='["all", "solid"]'>
                            <a className="d-block h-100" data-fancybox="solid" href="images/portfolio/swPlaneL.jpg">
                                <img className="img-fluid img-thumbnail" src="./images/portfolio/swPlaneS.jpg" alt="" />
                            </a>
                        </figure>

                        <figure className="item" data-groups='["all", "shop"]'>
                            <a className="d-block h-100" data-fancybox="shop" href="images/portfolio/pcUsaL.jpg">
                                <img className="img-fluid img-thumbnail" src="./images/portfolio/pcUsaS.jpg" alt="" />
                            </a>
                        </figure>

                        <figure className="item" data-groups='["all", "code"]'>
                            <a className="ajax-page-load" href="pages/project/project-5.html">
                                <img className="img-fluid img-thumbnail" src="./images/portfolio/wpfS.jpg" alt="" />
                                <div>
                                    <h5 className="name">Windows Presentation Foundation && Model-View-ViewModel</h5>
                                </div>
                            </a>
                        </figure>

                        <figure className="item" data-groups='["all", "hdr"]'>
                            <a className="d-block h-100" data-fancybox="hdr" href="images/portfolio/hdrWallL.jpg">
                                <img className="img-fluid img-thumbnail" src="./images/portfolio/hdrWallS.jpg" alt="" />
                            </a>
                        </figure>

                        <figure className="item" data-groups='["all", "hdr"]'>
                            <a className="d-block h-100" data-fancybox="hdr" href="images/portfolio/hdrChicagoL.jpg">
                                <img className="img-fluid img-thumbnail" src="./images/portfolio/hdrChicagoS.jpg" alt="" />
                            </a>
                        </figure>

                        <figure className="item" data-groups='["all", "code"]'>
                            <a className="ajax-page-load" href="pages/project/project-3.html">
                                <img className="img-fluid img-thumbnail" src="./images/portfolio/visionS.jpg" alt="" />
                                <div>
                                    <h5 className="name">Computer Vision</h5>
                                </div>
                            </a>
                        </figure>

                        <figure className="item" data-groups='["all", "shop"]'>
                            <a className="d-block h-100" data-fancybox="shop" href="images/portfolio/pcWarsawL.jpg">
                                <img className="img-fluid img-thumbnail" src="./images/portfolio/pcWarsawS.jpg" alt="" />
                            </a>
                        </figure>

                        <figure className="item" data-groups='["all", "photo"]'>
                            <a className="d-block h-100" data-fancybox="photo" href="images/portfolio/favCappadociaL.jpg">
                                <img className="img-fluid img-thumbnail" src="./images/portfolio/favCappadociaS.jpg" alt="" />
                            </a>
                        </figure>

                        <figure className="item" data-groups='["all", "code"]'>
                            <a className="ajax-page-load" href="pages/project/project-7.html">
                                <img className="img-fluid img-thumbnail" src="./images/portfolio/algoS.jpg" alt="" />
                                <div>
                                    <h5 className="name">Data Structures and Algorithms</h5>
                                </div>
                            </a>
                        </figure>

                        <figure className="item" data-groups='["all", "hdr"]'>
                            <a className="d-block h-100" data-fancybox="hdr" href="images/portfolio/hdrDancingL.jpg">
                                <img className="img-fluid img-thumbnail" src="./images/portfolio/hdrDancingS.jpg" alt="" />
                            </a>
                        </figure>

                        <figure className="item" data-groups='["all", "solid"]'>
                            <a className="d-block h-100" data-fancybox="solid" href="images/portfolio/swSkateL.jpg">
                                <img className="img-fluid img-thumbnail" src="./images/portfolio/swSkateS.jpg" alt="" />
                            </a>
                        </figure>

                        <figure className="item" data-groups='["all", "code"]'>
                            <a className="ajax-page-load" href="pages/project/project-4.html">
                                <img className="img-fluid img-thumbnail" src="./images/portfolio/finiteS.jpg" alt="" />
                                <div>
                                    <h5 className="name">Finite Element</h5>
                                </div>
                            </a>
                        </figure>

                        <figure className="item" data-groups='["all", "solid"]'>
                            <a className="d-block h-100" data-fancybox="solid" href="images/portfolio/swDriveL.jpg">
                                <img className="img-fluid img-thumbnail" src="./images/portfolio/swDriveS.jpg" alt="" />
                            </a>
                        </figure>

                        <figure className="item" data-groups='["all", "photo"]'>
                            <a className="d-block h-100" data-fancybox="photo" href="images/portfolio/favElephantL.jpg">
                                <img className="img-fluid img-thumbnail" src="./images/portfolio/favElephantS.jpg" alt="" />
                            </a>
                        </figure>

                        <figure className="item" data-groups='["all", "code"]'>
                            <a className="ajax-page-load" href="pages/project/project-1.html">
                                <img className="img-fluid img-thumbnail" src="./images/portfolio/lightS.jpg" alt="" />
                                <div>
                                    <h5 className="name">Personal Website - Light Version</h5>
                                </div>
                            </a>
                        </figure>

                        <figure className="item" data-groups='["all", "shop"]'>
                            <a className="d-block h-100" data-fancybox="shop" href="images/portfolio/pcSiemReapL.jpg">
                                <img className="img-fluid img-thumbnail" src="./images/portfolio/pcSiemReapS.jpg" alt="" />
                            </a>
                        </figure>

                        <figure className="item" data-groups='["all", "shop"]'>
                            <a className="d-block h-100" data-fancybox="shop" href="images/portfolio/psFlameL.jpg">
                                <img className="img-fluid img-thumbnail" src="./images/portfolio/psFlameS.jpg" alt="" />
                            </a>
                        </figure>

                        <figure className="item" data-groups='["all", "code"]'>
                            <a className="ajax-page-load" href="pages/project/project-2.html">
                                <img className="img-fluid img-thumbnail" src="./images/portfolio/darkS.jpg" alt="" />
                                <div>
                                    <h5 className="name">Personal Website - Dark Version</h5>
                                </div>
                            </a>
                        </figure>

                        <figure className="item" data-groups='["all", "photo"]'>
                            <a className="d-block h-100" data-fancybox="photo" href="images/portfolio/favHeadL.jpg">
                                <img className="img-fluid img-thumbnail" src="./images/portfolio/favHeadS.jpg" alt="" />
                            </a>
                        </figure>

                        <figure className="item" data-groups='["all", "photo"]'>
                            <a className="d-block h-100" data-fancybox="photo" href="images/portfolio/favPenangL.jpg">
                                <img className="img-fluid img-thumbnail" src="./images/portfolio/favPenangS.jpg" alt="" />
                            </a>
                        </figure>

                        <figure className="item" data-groups='["all", "photo"]'>
                            <a className="d-block h-100" data-fancybox="photo" href="images/portfolio/favSantoriniL.jpg">
                                <img className="img-fluid img-thumbnail" src="./images/portfolio/favSantoriniS.jpg" alt="" />
                            </a>
                        </figure>

                        <figure className="item" data-groups='["all", "solid"]'>
                            <a className="d-block h-100" data-fancybox="solid" href="images/portfolio/swBulbL.jpg">
                                <img className="img-fluid img-thumbnail" src="./images/portfolio/swBulbS.jpg" alt="" />
                            </a>
                        </figure>

                        <figure className="item" data-groups='["all", "photo"]'>
                            <a className="d-block h-100" data-fancybox="photo" href="images/portfolio/favTempleL.jpg">
                                <img className="img-fluid img-thumbnail" src="./images/portfolio/favTempleS.jpg" alt="" />
                            </a>
                        </figure>

                        <figure className="item" data-groups='["all", "code"]'>
                            <a className="ajax-page-load" href="pages/project/project-6.html">
                                <img className="img-fluid img-thumbnail" src="./images/portfolio/lorenzS.jpg" alt="" />
                                <div>
                                    <h5 className="name">Numerical Analysis</h5>
                                </div>
                            </a>
                        </figure>

                        <figure className="item" data-groups='["all", "shop"]'>
                            <a className="d-block h-100" data-fancybox="shop" href="images/portfolio/psSmokeL.jpg">
                                <img className="img-fluid img-thumbnail" src="./images/portfolio/psSmokeS.jpg" alt="" />
                            </a>
                        </figure>

                        <figure className="item" data-groups='["all", "photo"]'>
                            <a className="d-block h-100" data-fancybox="photo" href="images/portfolio/favCopenhagenL.jpg">
                                <img className="img-fluid img-thumbnail" src="./images/portfolio/favCopenhagenS.jpg" alt="" />
                            </a>
                        </figure>

                    </div>
                </div>
            </div>
        </section>

    )
};


const container = document.getElementById('portfolio_container');
const root = createRoot(container);
root.render(<PortfolioComponent />);

// light/src/app/portfolio/portfolio.component.ts
import { Component, OnInit } from '@angular/core';
import { GalleryItem } from './gallery-item';

@Component({
  selector: 'app-portfolio',
  templateUrl: './portfolio.component.html',
  styleUrls: ['./portfolio.component.css']
})
export class PortfolioComponent implements OnInit {
  galleryItems: GalleryItem[] = [];

  constructor() { }

  ngOnInit() {
    this.createGallery();
  }

  createGallery(): void {

    this.galleryItems.push({
      thumb: 'assets/images/portfolio/hdrCastleS.jpg',
      enlarge: 'assets/images/portfolio/hdrCastleL.jpg',
      filterGroup: 'hdr'
    });

    this.galleryItems.push({
      thumb: 'assets/images/portfolio/hdrChicagoS.jpg',
      enlarge: 'assets/images/portfolio/hdrChicagoL.jpg',
      filterGroup: 'hdr'
    });

    this.galleryItems.push({
      thumb: 'assets/images/portfolio/hdrDancingS.jpg',
      enlarge: 'assets/images/portfolio/hdrDancingL.jpg',
      filterGroup: 'hdr'
    });

    this.galleryItems.push({
      thumb: 'assets/images/portfolio/hdrWallS.jpg',
      enlarge: 'assets/images/portfolio/hdrWallL.jpg',
      filterGroup: 'hdr'
    });

    this.galleryItems.push({
      thumb: 'assets/images/portfolio/psJustinS.jpg',
      enlarge: 'assets/images/portfolio/psJustinL.jpg',
      filterGroup: 'ps'
    });

    this.galleryItems.push({
      thumb: 'assets/images/portfolio/psArmS.jpg',
      enlarge: 'assets/images/portfolio/psArmL.jpg',
      filterGroup: 'ps'
    });

    this.galleryItems.push({
      thumb: 'assets/images/portfolio/psFlameS.jpg',
      enlarge: 'assets/images/portfolio/psFlameL.jpg',
      filterGroup: 'ps'
    });

    this.galleryItems.push({
      thumb: 'assets/images/portfolio/psSmokeS.jpg',
      enlarge: 'assets/images/portfolio/psSmokeL.jpg',
      filterGroup: 'ps'
    });

    this.galleryItems.push({
      thumb: 'assets/images/portfolio/pcGdanskS.jpg',
      enlarge: 'assets/images/portfolio/pcGdanskL.jpg',
      filterGroup: 'pc'
    });

    this.galleryItems.push({
      thumb: 'assets/images/portfolio/pcMalaysiaS.jpg',
      enlarge: 'assets/images/portfolio/pcMalaysiaL.jpg',
      filterGroup: 'pc'
    });

    this.galleryItems.push({
      thumb: 'assets/images/portfolio/pcSingaporeS.jpg',
      enlarge: 'assets/images/portfolio/pcSingaporeL.jpg',
      filterGroup: 'pc'
    });

    this.galleryItems.push({
      thumb: 'assets/images/portfolio/pcSiemReapS.jpg',
      enlarge: 'assets/images/portfolio/pcSiemReapL.jpg',
      filterGroup: 'pc'
    });

    this.galleryItems.push({
      thumb: 'assets/images/portfolio/pcTibetS.jpg',
      enlarge: 'assets/images/portfolio/pcTibetL.jpg',
      filterGroup: 'pc'
    });

    this.galleryItems.push({
      thumb: 'assets/images/portfolio/pcUsaS.jpg',
      enlarge: 'assets/images/portfolio/pcUsaL.jpg',
      filterGroup: 'pc'
    });

    this.galleryItems.push({
      thumb: 'assets/images/portfolio/pcWarsawS.jpg',
      enlarge: 'assets/images/portfolio/pcWarsawL.jpg',
      filterGroup: 'pc'
    });

    this.galleryItems.push({
      thumb: 'assets/images/portfolio/pcXianS.jpg',
      enlarge: 'assets/images/portfolio/pcXianL.jpg',
      filterGroup: 'pc'
    });

    this.galleryItems.push({
      thumb: 'assets/images/portfolio/favBeachS.jpg',
      enlarge: 'assets/images/portfolio/favBeachL.jpg',
      filterGroup: 'fav'
    });

    this.galleryItems.push({
      thumb: 'assets/images/portfolio/favCappadociaS.jpg',
      enlarge: 'assets/images/portfolio/favCappadociaL.jpg',
      filterGroup: 'fav'
    });

    this.galleryItems.push({
      thumb: 'assets/images/portfolio/favColorS.jpg',
      enlarge: 'assets/images/portfolio/favColorL.jpg',
      filterGroup: 'fav'
    });

    this.galleryItems.push({
      thumb: 'assets/images/portfolio/favCopenhagenS.jpg',
      enlarge: 'assets/images/portfolio/favCopenhagenL.jpg',
      filterGroup: 'fav'
    });

    this.galleryItems.push({
      thumb: 'assets/images/portfolio/favElephantS.jpg',
      enlarge: 'assets/images/portfolio/favElephantL.jpg',
      filterGroup: 'fav'
    });

    this.galleryItems.push({
      thumb: 'assets/images/portfolio/favHeadS.jpg',
      enlarge: 'assets/images/portfolio/favHeadL.jpg',
      filterGroup: 'fav'
    });

    this.galleryItems.push({
      thumb: 'assets/images/portfolio/favIstanbulS.jpg',
      enlarge: 'assets/images/portfolio/favIstanbulL.jpg',
      filterGroup: 'fav'
    });

    this.galleryItems.push({
      thumb: 'assets/images/portfolio/favPandaS.jpg',
      enlarge: 'assets/images/portfolio/favPandaL.jpg',
      filterGroup: 'fav'
    });

    this.galleryItems.push({
      thumb: 'assets/images/portfolio/favPenangS.jpg',
      enlarge: 'assets/images/portfolio/favPenangL.jpg',
      filterGroup: 'fav'
    });

    this.galleryItems.push({
      thumb: 'assets/images/portfolio/favSantoriniS.jpg',
      enlarge: 'assets/images/portfolio/favSantoriniL.jpg',
      filterGroup: 'fav'
    });

    this.galleryItems.push({
      thumb: 'assets/images/portfolio/favRuinS.jpg',
      enlarge: 'assets/images/portfolio/favRuinL.jpg',
      filterGroup: 'fav'
    });

    this.galleryItems.push({
      thumb: 'assets/images/portfolio/favTempleS.jpg',
      enlarge: 'assets/images/portfolio/favTempleL.jpg',
      filterGroup: 'fav'
    });

    this.galleryItems.push({
      thumb: 'assets/images/portfolio/swBulbS.jpg',
      enlarge: 'assets/images/portfolio/swBulbL.jpg',
      filterGroup: 'sw'
    });

    this.galleryItems.push({
      thumb: 'assets/images/portfolio/swDriveS.jpg',
      enlarge: 'assets/images/portfolio/swDriveL.jpg',
      filterGroup: 'sw'
    });

    this.galleryItems.push({
      thumb: 'assets/images/portfolio/swPlaneS.jpg',
      enlarge: 'assets/images/portfolio/swPlaneL.jpg',
      filterGroup: 'sw'
    });

    this.galleryItems.push({
      thumb: 'assets/images/portfolio/swSkateS.jpg',
      enlarge: 'assets/images/portfolio/swSkateL.jpg',
      filterGroup: 'sw'
    });
  }
}

<!-- Portfolio -->
<section id="portfolio">
  <div class="container text-center">
    <div class="row">
      <div class="col-lg-12 text-center">
        <h2 class="section-heading text-uppercase" id="portfolioLink">Portfolio</h2>
        <h3 class="section-subheading text-muted">Samples of my artistic and creative works</h3>
      </div>
    </div>
    <!-- Grid row -->
    <div class="row">
      <!-- Grid column -->
      <div class="col-md-12 justify-content-center mb-5 animated hiding" data-animation="zoomIn" >
        <button type="button" class="btn btn-outline-black" data-filter="*">All</button>
        <button type="button" class="btn btn-outline-black" data-filter=".hdr">HDR</button>
        <button type="button" class="btn btn-outline-black" data-filter=".ps">Photoshop</button>
        <button type="button" class="btn btn-outline-black" data-filter=".fav">Favorites</button>
        <button type="button" class="btn btn-outline-black" data-filter=".pc">Postcards</button>
        <button type="button" class="btn btn-outline-black" data-filter=".sw">SolidWorks</button>
      </div>
      <!-- Grid column -->
    </div>
    <!-- Grid row -->

    <!-- Grid row -->
    <div class="row no-gutters text-center animated hiding" id="gallery" data-animation="fadeIn" data-delay="400">
      <div *ngFor="let galleryItem of galleryItems" attr.class="col-lg-3 col-md-4 col-sm-6 mix {{galleryItem.filterGroup}}">
        <a class="d-block h-100" attr.data-fancybox="{{galleryItem.filterGroup}}" attr.href="{{galleryItem.enlarge}}">
          <img class="img-fluid img-thumbnail" attr.src="{{galleryItem.thumb}}" alt="">
        </a>
      </div>
    </div>
    <!-- Grid row -->

    <!-- /.container -->
  </div>
</section>
